In [1]:
from __future__ import print_function
import torch

In [3]:
print(torch.cuda.is_available())

True


In [26]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 9.1084e-44, 0.0000e+00],
        [1.3869e-23, 3.0760e-41, 1.3917e-23]])


In [27]:
y = torch.rand(5,3)
print(y)

tensor([[0.0320, 0.2492, 0.8793],
        [0.9662, 0.6004, 0.5999],
        [0.1179, 0.4731, 0.9428],
        [0.2360, 0.2096, 0.4589],
        [0.3165, 0.1245, 0.1567]])


In [28]:
z=torch.zeros(5,3, dtype=torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [31]:
a=torch.tensor([1.5, 3])
print(a)

tensor([1.5000, 3.0000])
